# Generated by Django 5.1.7 on 2025-04-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('experience', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_approved', 'Не подтвержден'), ('moderated', 'Прошел модерацию'), ('spam', 'Спам'), ('approved', 'Подтвержден'), ('in_awaiting', 'В ожидании'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='not_approved', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('appountment_date', models.DateTimeField(blank=True, null=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.master')),
            ],
        ),
    ]
